# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/la$
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire h$
      # use `-browsers` prefix for selen$
      - image: circleci/python:3.6.1

      # Specify service dependencies her$
      # CircleCI maintains a library of $
      # documented at https://circleci.c$
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest$
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint